# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1273, 739)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.editPopulation = QtGui.QLineEdit(self.groupBox_4)
        self.editPopulation.setObjectName(_fromUtf8("editPopulation"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.editPopulation)
        self.label_29 = QtGui.QLabel(self.groupBox_4)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.editMaxGenerations = QtGui.QLineEdit(self.groupBox_4)
        self.editMaxGenerations.setObjectName(_fromUtf8("editMaxGenerations"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.editMaxGenerations)
        self.label_30 = QtGui.QLabel(self.groupBox_4)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_30)
        self.editCrossoverProbability = QtGui.QLineEdit(self.groupBox_4)
        self.editCrossoverProbability.setObjectName(_fromUtf8("editCrossoverProbability"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.editCrossoverProbability)
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_31)
        self.editMutationProbability = QtGui.QLineEdit(self.groupBox_4)
        self.editMutationProbability.setObjectName(_fromUtf8("editMutationProbability"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.editMutationProbability)
        self.label_32 = QtGui.QLabel(self.groupBox_4)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_32)
        self.editMigrationProbability = QtGui.QLineEdit(self.groupBox_4)
        self.editMigrationProbability.setObjectName(_fromUtf8("editMigrationProbability"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.editMigrationProbability)
        self.label_33 = QtGui.QLabel(self.groupBox_4)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtGui.QLabel(self.groupBox_4)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtGui.QLabel(self.groupBox_4)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtGui.QLabel(self.groupBox_4)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_36)
        self.comboElitismMode = QtGui.QComboBox(self.groupBox_4)
        self.comboElitismMode.setObjectName(_fromUtf8("comboElitismMode"))
        self.comboElitismMode.addItem(_fromUtf8(""))
        self.comboElitismMode.addItem(_fromUtf8(""))
        self.comboElitismMode.addItem(_fromUtf8(""))
        self.comboElitismMode.addItem(_fromUtf8(""))
        self.comboElitismMode.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.comboElitismMode)
        self.comboMutationMode = QtGui.QComboBox(self.groupBox_4)
        self.comboMutationMode.setObjectName(_fromUtf8("comboMutationMode"))
        self.comboMutationMode.addItem(_fromUtf8(""))
        self.comboMutationMode.addItem(_fromUtf8(""))
        self.comboMutationMode.addItem(_fromUtf8(""))
        self.comboMutationMode.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.comboMutationMode)
        self.comboCrossoverMode = QtGui.QComboBox(self.groupBox_4)
        self.comboCrossoverMode.setObjectName(_fromUtf8("comboCrossoverMode"))
        self.comboCrossoverMode.addItem(_fromUtf8(""))
        self.comboCrossoverMode.addItem(_fromUtf8(""))
        self.comboCrossoverMode.addItem(_fromUtf8(""))
        self.comboCrossoverMode.addItem(_fromUtf8(""))
        self.comboCrossoverMode.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.comboCrossoverMode)
        self.comboEvolutionaryMode = QtGui.QComboBox(self.groupBox_4)
        self.comboEvolutionaryMode.setObjectName(_fromUtf8("comboEvolutionaryMode"))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.comboEvolutionaryMode.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.comboEvolutionaryMode)
        self.gridLayout_6.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.editBalance = QtGui.QLineEdit(self.groupBox_3)
        self.editBalance.setObjectName(_fromUtf8("editBalance"))
        self.horizontalLayout_4.addWidget(self.editBalance)
        self.comboAccountCurrency = QtGui.QComboBox(self.groupBox_3)
        self.comboAccountCurrency.setObjectName(_fromUtf8("comboAccountCurrency"))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.comboAccountCurrency.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboAccountCurrency)
        self.formLayout_5.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_18)
        self.editLeverage = QtGui.QLineEdit(self.groupBox_3)
        self.editLeverage.setObjectName(_fromUtf8("editLeverage"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.editLeverage)
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_19)
        self.editContractSize = QtGui.QLineEdit(self.groupBox_3)
        self.editContractSize.setObjectName(_fromUtf8("editContractSize"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.editContractSize)
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_21)
        self.editStopOut = QtGui.QLineEdit(self.groupBox_3)
        self.editStopOut.setObjectName(_fromUtf8("editStopOut"))
        self.formLayout_5.setWidget(5, QtGui.QFormLayout.FieldRole, self.editStopOut)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_23)
        self.editSpread = QtGui.QLineEdit(self.groupBox_3)
        self.editSpread.setObjectName(_fromUtf8("editSpread"))
        self.formLayout_5.setWidget(7, QtGui.QFormLayout.FieldRole, self.editSpread)
        self.editDigits = QtGui.QLineEdit(self.groupBox_3)
        self.editDigits.setObjectName(_fromUtf8("editDigits"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.editDigits)
        self.label_40 = QtGui.QLabel(self.groupBox_3)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_40)
        self.editMinLotSize = QtGui.QLineEdit(self.groupBox_3)
        self.editMinLotSize.setObjectName(_fromUtf8("editMinLotSize"))
        self.formLayout_5.setWidget(8, QtGui.QFormLayout.FieldRole, self.editMinLotSize)
        self.editMinimumStop = QtGui.QLineEdit(self.groupBox_3)
        self.editMinimumStop.setObjectName(_fromUtf8("editMinimumStop"))
        self.formLayout_5.setWidget(6, QtGui.QFormLayout.FieldRole, self.editMinimumStop)
        self.horizontalLayout_5.addLayout(self.formLayout_5)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 1, 2, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.checkOptimize = QtGui.QCheckBox(self.groupBox_2)
        self.checkOptimize.setText(_fromUtf8(""))
        self.checkOptimize.setChecked(False)
        self.checkOptimize.setObjectName(_fromUtf8("checkOptimize"))
        self.gridLayout_5.addWidget(self.checkOptimize, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.comboOptimizationType = QtGui.QComboBox(self.groupBox_2)
        self.comboOptimizationType.setObjectName(_fromUtf8("comboOptimizationType"))
        self.comboOptimizationType.addItem(_fromUtf8(""))
        self.comboOptimizationType.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboOptimizationType, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.comboGoal = QtGui.QComboBox(self.groupBox_2)
        self.comboGoal.setObjectName(_fromUtf8("comboGoal"))
        self.comboGoal.addItem(_fromUtf8(""))
        self.comboGoal.addItem(_fromUtf8(""))
        self.comboGoal.addItem(_fromUtf8(""))
        self.comboGoal.addItem(_fromUtf8(""))
        self.comboGoal.addItem(_fromUtf8(""))
        self.comboGoal.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboGoal, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 3, 0, 1, 1)
        self.spinNumCores = QtGui.QSpinBox(self.groupBox_2)
        self.spinNumCores.setMinimum(1)
        self.spinNumCores.setMaximum(8)
        self.spinNumCores.setProperty("value", 8)
        self.spinNumCores.setObjectName(_fromUtf8("spinNumCores"))
        self.gridLayout_5.addWidget(self.spinNumCores, 3, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 4, 0, 1, 1)
        self.checkStopIfConverged = QtGui.QCheckBox(self.groupBox_2)
        self.checkStopIfConverged.setText(_fromUtf8(""))
        self.checkStopIfConverged.setChecked(True)
        self.checkStopIfConverged.setObjectName(_fromUtf8("checkStopIfConverged"))
        self.gridLayout_5.addWidget(self.checkStopIfConverged, 4, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 5, 0, 1, 1)
        self.checkDiscardAsymetric = QtGui.QCheckBox(self.groupBox_2)
        self.checkDiscardAsymetric.setText(_fromUtf8(""))
        self.checkDiscardAsymetric.setChecked(True)
        self.checkDiscardAsymetric.setObjectName(_fromUtf8("checkDiscardAsymetric"))
        self.gridLayout_5.addWidget(self.checkDiscardAsymetric, 5, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 6, 0, 1, 1)
        self.editMinTrades = QtGui.QLineEdit(self.groupBox_2)
        self.editMinTrades.setObjectName(_fromUtf8("editMinTrades"))
        self.gridLayout_5.addWidget(self.editMinTrades, 6, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_4)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.comboStrategy = QtGui.QComboBox(self.groupBox)
        self.comboStrategy.setObjectName(_fromUtf8("comboStrategy"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboStrategy)
        self.label_38 = QtGui.QLabel(self.groupBox)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_38)
        self.splitter = QtGui.QSplitter(self.groupBox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.editPortfolioStrategies = QtGui.QLineEdit(self.splitter)
        self.editPortfolioStrategies.setObjectName(_fromUtf8("editPortfolioStrategies"))
        self.buttonAddStrategy = QtGui.QPushButton(self.splitter)
        self.buttonAddStrategy.setObjectName(_fromUtf8("buttonAddStrategy"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.splitter)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.editPair = QtGui.QLineEdit(self.groupBox)
        self.editPair.setObjectName(_fromUtf8("editPair"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.editPair)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.dateFrom = QtGui.QDateEdit(self.groupBox)
        self.dateFrom.setDateTime(QtCore.QDateTime(QtCore.QDate(1980, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateFrom.setDate(QtCore.QDate(1980, 1, 1))
        self.dateFrom.setObjectName(_fromUtf8("dateFrom"))
        self.horizontalLayout_2.addWidget(self.dateFrom)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dateTo = QtGui.QDateEdit(self.groupBox)
        self.dateTo.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTo.setDate(QtCore.QDate(2020, 1, 1))
        self.dateTo.setObjectName(_fromUtf8("dateTo"))
        self.horizontalLayout_3.addWidget(self.dateTo)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_39 = QtGui.QLabel(self.groupBox)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_39)
        self.editDataTF = QtGui.QLineEdit(self.groupBox)
        self.editDataTF.setObjectName(_fromUtf8("editDataTF"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.editDataTF)
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_37)
        self.editSet = QtGui.QLineEdit(self.groupBox)
        self.editSet.setObjectName(_fromUtf8("editSet"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.editSet)
        self.label_41 = QtGui.QLabel(self.groupBox)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.SpanningRole, self.label_41)
        self.editRateRequirements = QtGui.QLineEdit(self.groupBox)
        self.editRateRequirements.setObjectName(_fromUtf8("editRateRequirements"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.editRateRequirements)
        self.label_42 = QtGui.QLabel(self.groupBox)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.label_42)
        self.editSymbolRequirements = QtGui.QLineEdit(self.groupBox)
        self.editSymbolRequirements.setObjectName(_fromUtf8("editSymbolRequirements"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.SpanningRole, self.editSymbolRequirements)
        self.editTimeFrameRequirements = QtGui.QLineEdit(self.groupBox)
        self.editTimeFrameRequirements.setObjectName(_fromUtf8("editTimeFrameRequirements"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.SpanningRole, self.editTimeFrameRequirements)
        self.label_43 = QtGui.QLabel(self.groupBox)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.label_43)
        self.buttonModifySetFile = QtGui.QPushButton(self.groupBox)
        self.buttonModifySetFile.setObjectName(_fromUtf8("buttonModifySetFile"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.buttonModifySetFile)
        self.buttonLoadSetFile = QtGui.QPushButton(self.groupBox)
        self.buttonLoadSetFile.setObjectName(_fromUtf8("buttonLoadSetFile"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.buttonLoadSetFile)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonStartTest = QtGui.QPushButton(self.groupBox)
        self.buttonStartTest.setObjectName(_fromUtf8("buttonStartTest"))
        self.gridLayout_3.addWidget(self.buttonStartTest, 1, 0, 1, 1)
        self.buttonStopOptimization = QtGui.QPushButton(self.groupBox)
        self.buttonStopOptimization.setEnabled(False)
        self.buttonStopOptimization.setObjectName(_fromUtf8("buttonStopOptimization"))
        self.gridLayout_3.addWidget(self.buttonStopOptimization, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(1200, 0))
        self.graphicsView.setTransformationAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setResizeAnchor(QtGui.QGraphicsView.AnchorViewCenter)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout_4.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.labelTotalTrades = QtGui.QLabel(self.tab_2)
        self.labelTotalTrades.setText(_fromUtf8(""))
        self.labelTotalTrades.setObjectName(_fromUtf8("labelTotalTrades"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelTotalTrades)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.labelLongs = QtGui.QLabel(self.tab_2)
        self.labelLongs.setText(_fromUtf8(""))
        self.labelLongs.setObjectName(_fromUtf8("labelLongs"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelLongs)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.labelShorts = QtGui.QLabel(self.tab_2)
        self.labelShorts.setText(_fromUtf8(""))
        self.labelShorts.setObjectName(_fromUtf8("labelShorts"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelShorts)
        self.gridLayout_8.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.labelFinalBalance = QtGui.QLabel(self.tab_2)
        self.labelFinalBalance.setText(_fromUtf8(""))
        self.labelFinalBalance.setObjectName(_fromUtf8("labelFinalBalance"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelFinalBalance)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.labelMaxDD = QtGui.QLabel(self.tab_2)
        self.labelMaxDD.setText(_fromUtf8(""))
        self.labelMaxDD.setObjectName(_fromUtf8("labelMaxDD"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelMaxDD)
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.labelMaxDDLength = QtGui.QLabel(self.tab_2)
        self.labelMaxDDLength.setText(_fromUtf8(""))
        self.labelMaxDDLength.setObjectName(_fromUtf8("labelMaxDDLength"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelMaxDDLength)
        self.gridLayout_8.addLayout(self.formLayout_4, 0, 1, 1, 1)
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.labelPF = QtGui.QLabel(self.tab_2)
        self.labelPF.setText(_fromUtf8(""))
        self.labelPF.setObjectName(_fromUtf8("labelPF"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelPF)
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.labelR2 = QtGui.QLabel(self.tab_2)
        self.labelR2.setText(_fromUtf8(""))
        self.labelR2.setObjectName(_fromUtf8("labelR2"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelR2)
        self.label_27 = QtGui.QLabel(self.tab_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_27)
        self.labelUlcerIndex = QtGui.QLabel(self.tab_2)
        self.labelUlcerIndex.setText(_fromUtf8(""))
        self.labelUlcerIndex.setObjectName(_fromUtf8("labelUlcerIndex"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelUlcerIndex)
        self.gridLayout_8.addLayout(self.formLayout_6, 0, 2, 1, 1)
        self.tableTest = QtGui.QTableWidget(self.tab_2)
        self.tableTest.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableTest.setAlternatingRowColors(True)
        self.tableTest.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableTest.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableTest.setRowCount(0)
        self.tableTest.setColumnCount(14)
        self.tableTest.setObjectName(_fromUtf8("tableTest"))
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableTest.setHorizontalHeaderItem(13, item)
        self.tableTest.horizontalHeader().setDefaultSectionSize(70)
        self.tableTest.horizontalHeader().setMinimumSectionSize(30)
        self.tableTest.horizontalHeader().setSortIndicatorShown(False)
        self.tableTest.horizontalHeader().setStretchLastSection(True)
        self.tableTest.verticalHeader().setVisible(False)
        self.tableTest.verticalHeader().setDefaultSectionSize(20)
        self.tableTest.verticalHeader().setHighlightSections(False)
        self.tableTest.verticalHeader().setStretchLastSection(False)
        self.gridLayout_8.addWidget(self.tableTest, 1, 0, 1, 3)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tableOptimization = QtGui.QTableWidget(self.tab_3)
        self.tableOptimization.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableOptimization.setAlternatingRowColors(True)
        self.tableOptimization.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableOptimization.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableOptimization.setRowCount(0)
        self.tableOptimization.setColumnCount(11)
        self.tableOptimization.setObjectName(_fromUtf8("tableOptimization"))
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableOptimization.setHorizontalHeaderItem(10, item)
        self.tableOptimization.horizontalHeader().setDefaultSectionSize(70)
        self.tableOptimization.horizontalHeader().setMinimumSectionSize(30)
        self.tableOptimization.horizontalHeader().setSortIndicatorShown(False)
        self.tableOptimization.horizontalHeader().setStretchLastSection(True)
        self.tableOptimization.verticalHeader().setVisible(False)
        self.tableOptimization.verticalHeader().setDefaultSectionSize(20)
        self.tableOptimization.verticalHeader().setHighlightSections(False)
        self.tableOptimization.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableOptimization, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 2)
        self.labelInfo = QtGui.QLabel(self.centralWidget)
        self.labelInfo.setObjectName(_fromUtf8("labelInfo"))
        self.gridLayout_9.addWidget(self.labelInfo, 1, 0, 1, 1)
        self.labelVersions = QtGui.QLabel(self.centralWidget)
        self.labelVersions.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelVersions.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVersions.setObjectName(_fromUtf8("labelVersions"))
        self.gridLayout_9.addWidget(self.labelVersions, 1, 1, 1, 1)
        self.tabWidget.raise_()
        self.labelVersions.raise_()
        self.labelInfo.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboOptimizationType.setCurrentIndex(1)
        self.comboStrategy.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Asirikuy Visual Tester", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Advanced Optimization Options", None))
        self.label_28.setText(_translate("MainWindow", "Population", None))
        self.editPopulation.setText(_translate("MainWindow", "30", None))
        self.label_29.setText(_translate("MainWindow", "Max generations", None))
        self.editMaxGenerations.setToolTip(_translate("MainWindow", "Max number of generations. 0 for unlimited", None))
        self.editMaxGenerations.setText(_translate("MainWindow", "10000", None))
        self.label_30.setText(_translate("MainWindow", "Crossover Probab.", None))
        self.editCrossoverProbability.setText(_translate("MainWindow", "0.90", None))
        self.label_31.setText(_translate("MainWindow", "Mutation Probab.", None))
        self.editMutationProbability.setText(_translate("MainWindow", "0.20", None))
        self.label_32.setText(_translate("MainWindow", "Migration Probab.", None))
        self.editMigrationProbability.setText(_translate("MainWindow", "0.00", None))
        self.label_33.setText(_translate("MainWindow", "Evolutionary Mode", None))
        self.label_34.setText(_translate("MainWindow", "Elitism Mode", None))
        self.label_35.setText(_translate("MainWindow", "Mutation Mode", None))
        self.label_36.setText(_translate("MainWindow", "Crossover Mode", None))
        self.comboElitismMode.setItemText(0, _translate("MainWindow", "Unknown", None))
        self.comboElitismMode.setItemText(1, _translate("MainWindow", "Parents Survive", None))
        self.comboElitismMode.setItemText(2, _translate("MainWindow", "One Parent Survive", None))
        self.comboElitismMode.setItemText(3, _translate("MainWindow", "Parents Die", None))
        self.comboElitismMode.setItemText(4, _translate("MainWindow", "Rescore Parents", None))
        self.comboMutationMode.setItemText(0, _translate("MainWindow", "Single Point Drift", None))
        self.comboMutationMode.setItemText(1, _translate("MainWindow", "Single Point Randomize", None))
        self.comboMutationMode.setItemText(2, _translate("MainWindow", "Multipoint", None))
        self.comboMutationMode.setItemText(3, _translate("MainWindow", "All Point", None))
        self.comboCrossoverMode.setItemText(0, _translate("MainWindow", "Single Points", None))
        self.comboCrossoverMode.setItemText(1, _translate("MainWindow", "Double Points", None))
        self.comboCrossoverMode.setItemText(2, _translate("MainWindow", "Mean", None))
        self.comboCrossoverMode.setItemText(3, _translate("MainWindow", "Mixing", None))
        self.comboCrossoverMode.setItemText(4, _translate("MainWindow", "Allele Mixing", None))
        self.comboEvolutionaryMode.setItemText(0, _translate("MainWindow", "Darwin", None))
        self.comboEvolutionaryMode.setItemText(1, _translate("MainWindow", "Lamarck Parents", None))
        self.comboEvolutionaryMode.setItemText(2, _translate("MainWindow", "Lamarck Children", None))
        self.comboEvolutionaryMode.setItemText(3, _translate("MainWindow", "Lamarck All", None))
        self.comboEvolutionaryMode.setItemText(4, _translate("MainWindow", "Baldwin Parents", None))
        self.comboEvolutionaryMode.setItemText(5, _translate("MainWindow", "Baldwin Children", None))
        self.comboEvolutionaryMode.setItemText(6, _translate("MainWindow", "Baldwin All", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Account Options", None))
        self.label_17.setText(_translate("MainWindow", "Initial Balance", None))
        self.editBalance.setText(_translate("MainWindow", "100000", None))
        self.comboAccountCurrency.setItemText(0, _translate("MainWindow", "USD", None))
        self.comboAccountCurrency.setItemText(1, _translate("MainWindow", "EUR", None))
        self.comboAccountCurrency.setItemText(2, _translate("MainWindow", "GBP", None))
        self.comboAccountCurrency.setItemText(3, _translate("MainWindow", "CHF", None))
        self.comboAccountCurrency.setItemText(4, _translate("MainWindow", "JPY", None))
        self.comboAccountCurrency.setItemText(5, _translate("MainWindow", "AUD", None))
        self.comboAccountCurrency.setItemText(6, _translate("MainWindow", "CAD", None))
        self.label_18.setText(_translate("MainWindow", "Leverage", None))
        self.editLeverage.setText(_translate("MainWindow", "200", None))
        self.label_19.setText(_translate("MainWindow", "Contract size", None))
        self.editContractSize.setText(_translate("MainWindow", "100000", None))
        self.label_20.setText(_translate("MainWindow", "Digits(s)", None))
        self.label_21.setText(_translate("MainWindow", "Stop out %", None))
        self.editStopOut.setText(_translate("MainWindow", "1", None))
        self.label_22.setText(_translate("MainWindow", "Minimum stop", None))
        self.label_23.setText(_translate("MainWindow", "Spread(s)", None))
        self.editSpread.setText(_translate("MainWindow", "0.0001", None))
        self.editDigits.setText(_translate("MainWindow", "5", None))
        self.label_40.setText(_translate("MainWindow", "Min Lot Size", None))
        self.editMinLotSize.setText(_translate("MainWindow", "0.01", None))
        self.editMinimumStop.setText(_translate("MainWindow", "0.0010", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Optimization Options", None))
        self.label_9.setText(_translate("MainWindow", "Optimize", None))
        self.label_10.setText(_translate("MainWindow", "Type", None))
        self.comboOptimizationType.setItemText(0, _translate("MainWindow", "Brute Force", None))
        self.comboOptimizationType.setItemText(1, _translate("MainWindow", "Genetic", None))
        self.label_12.setText(_translate("MainWindow", "Goal", None))
        self.comboGoal.setItemText(0, _translate("MainWindow", "Balance", None))
        self.comboGoal.setItemText(1, _translate("MainWindow", "Max DD", None))
        self.comboGoal.setItemText(2, _translate("MainWindow", "Max DD Length", None))
        self.comboGoal.setItemText(3, _translate("MainWindow", "Profit Factor", None))
        self.comboGoal.setItemText(4, _translate("MainWindow", "R2", None))
        self.comboGoal.setItemText(5, _translate("MainWindow", "Ulcer Index", None))
        self.label_11.setText(_translate("MainWindow", "Num Cores", None))
        self.label_24.setText(_translate("MainWindow", "Stop if converged", None))
        self.label_25.setText(_translate("MainWindow", "Discard asymetric", None))
        self.label_26.setText(_translate("MainWindow", "Min trades/Year", None))
        self.editMinTrades.setText(_translate("MainWindow", "20", None))
        self.groupBox.setTitle(_translate("MainWindow", "Strategy Options", None))
        self.label.setText(_translate("MainWindow", "Stategy", None))
        self.label_38.setText(_translate("MainWindow", "Portfolio Strat.", None))
        self.buttonAddStrategy.setText(_translate("MainWindow", "Add", None))
        self.label_2.setText(_translate("MainWindow", "Pair(s)", None))
        self.editPair.setText(_translate("MainWindow", "EURUSD", None))
        self.label_3.setText(_translate("MainWindow", "From", None))
        self.dateFrom.setDisplayFormat(_translate("MainWindow", "d/M/yyyy", None))
        self.label_4.setText(_translate("MainWindow", "To", None))
        self.dateTo.setDisplayFormat(_translate("MainWindow", "d/M/yyyy", None))
        self.label_39.setText(_translate("MainWindow", "Data T. Frame", None))
        self.editDataTF.setText(_translate("MainWindow", "60", None))
        self.label_37.setText(_translate("MainWindow", "Set(s)", None))
        self.label_41.setText(_translate("MainWindow", "Rate requirements", None))
        self.label_42.setText(_translate("MainWindow", "Symbol requirements", None))
        self.label_43.setText(_translate("MainWindow", "Timeframe requirements", None))
        self.buttonModifySetFile.setText(_translate("MainWindow", "Modify set file", None))
        self.buttonLoadSetFile.setText(_translate("MainWindow", "Load set file", None))
        self.buttonStartTest.setText(_translate("MainWindow", "Start Test / Optimization", None))
        self.buttonStopOptimization.setText(_translate("MainWindow", "Stop Optimization", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Graphic result", None))
        self.label_5.setText(_translate("MainWindow", "Total Trades", None))
        self.label_6.setText(_translate("MainWindow", "Longs", None))
        self.label_7.setText(_translate("MainWindow", "Shorts", None))
        self.label_8.setText(_translate("MainWindow", "Final Balance", None))
        self.label_13.setText(_translate("MainWindow", "Max DD", None))
        self.label_14.setText(_translate("MainWindow", "Max DD Length", None))
        self.label_15.setText(_translate("MainWindow", "Profit Factor", None))
        self.label_16.setText(_translate("MainWindow", "R2", None))
        self.label_27.setText(_translate("MainWindow", "Ulcer Index", None))
        self.tableTest.setSortingEnabled(False)
        item = self.tableTest.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order", None))
        item = self.tableTest.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type", None))
        item = self.tableTest.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Open Time", None))
        item = self.tableTest.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Close Time", None))
        item = self.tableTest.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Open Price", None))
        item = self.tableTest.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Close Price", None))
        item = self.tableTest.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Lots", None))
        item = self.tableTest.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Profit", None))
        item = self.tableTest.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "SL", None))
        item = self.tableTest.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "TP", None))
        item = self.tableTest.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Balance", None))
        item = self.tableTest.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.tableTest.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Symbol", None))
        item = self.tableTest.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Swap", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Test Results", None))
        self.tableOptimization.setSortingEnabled(False)
        item = self.tableOptimization.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Iteration", None))
        item = self.tableOptimization.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Num Trades", None))
        item = self.tableOptimization.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Profit", None))
        item = self.tableOptimization.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "max DD", None))
        item = self.tableOptimization.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "DD Length", None))
        item = self.tableOptimization.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PF", None))
        item = self.tableOptimization.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "R2", None))
        item = self.tableOptimization.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Ulcer Index", None))
        item = self.tableOptimization.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Shorts", None))
        item = self.tableOptimization.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Longs", None))
        item = self.tableOptimization.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Parameters", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Optimization Result", None))
        self.labelInfo.setText(_translate("MainWindow", "TextLabel", None))
        self.labelVersions.setText(_translate("MainWindow", "TextLabel", None))

