/**
 * @file
 * @brief     Python-friendly API for TradingStrategies library
 * @details   Provides a simplified C API that can be easily called from Python
 *            using ctypes or CFFI. Removes DLL-specific calling conventions
 *            and file-based I/O dependencies.
 * 
 * @author    Refactoring for Python integration
 * @date      2024
 */

#ifndef TRADING_STRATEGIES_PYTHON_API_H_
#define TRADING_STRATEGIES_PYTHON_API_H_

#include "AsirikuyDefines.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
typedef struct PythonStrategyInput PythonStrategyInput;
typedef struct PythonStrategyOutput PythonStrategyOutput;

/**
 * Simplified input structure for Python
 * Flattens nested structures into arrays for easier Python interop
 */
struct PythonStrategyInput {
    /* Strategy identification */
    int strategy_id;              /* INTERNAL_STRATEGY_ID */
    int instance_id;               /* STRATEGY_INSTANCE_ID */
    
    /* Market data */
    char* symbol;                  /* Trade symbol (e.g., "EURUSD") */
    double bid;
    double ask;
    time_t current_time;
    
    /* Account information */
    double account_balance;
    double account_equity;
    char* account_currency;
    
    /* Rates data - one timeframe at a time
     * For multiple timeframes, call multiple times or extend structure
     */
    int rates_count;               /* Number of bars */
    double* rates_time;            /* Array of timestamps */
    double* rates_open;            /* Array of open prices */
    double* rates_high;            /* Array of high prices */
    double* rates_low;             /* Array of low prices */
    double* rates_close;           /* Array of close prices */
    double* rates_volume;          /* Array of volumes */
    
    /* Settings array - flattened for Python
     * Maps to StrategyParams->settings array
     */
    double* settings;
    int settings_count;
    
    /* Open orders */
    int orders_count;
    int* order_numbers;
    int* order_types;              /* OrderType enum values */
    double* order_open_prices;
    double* order_stop_loss;
    double* order_take_profit;
    int* order_statuses;           /* OrderStatus enum values */
    time_t* order_timestamps;
};

/**
 * Output structure for Python
 * Contains all results from strategy execution
 */
struct PythonStrategyOutput {
    int return_code;               /* AsirikuyReturnCode */
    
    /* Order signals generated by strategy */
    int signals_count;
    int* signal_types;             /* OrderType enum: BUY, SELL, etc. */
    double* signal_prices;
    double* signal_stop_loss;
    double* signal_take_profit;
    int* signal_actions;           /* Action: OPEN, MODIFY, CLOSE */
    
    /* UI values (optional, for monitoring) */
    int ui_values_count;
    char** ui_names;               /* Array of UI variable names */
    double* ui_values;             /* Array of UI variable values */
    
    /* Status message */
    char status_message[256];
    
    /* Internal pointers - do not access from Python */
    void* _internal_data;          /* For internal memory management */
};

/**
 * Main entry point for Python
 * 
 * This function:
 * 1. Converts PythonStrategyInput to internal StrategyParams
 * 2. Calls runStrategy()
 * 3. Converts StrategyResults to PythonStrategyOutput
 * 4. Returns return code
 * 
 * @param input  Input data from Python (must not be NULL)
 * @param output Output data for Python (must not be NULL, will be populated)
 * 
 * @return AsirikuyReturnCode (SUCCESS on success, error code on failure)
 * 
 * @note Memory for output arrays is allocated by this function.
 *       Call trading_strategies_free_output() to free memory.
 */
int trading_strategies_run(
    const PythonStrategyInput* input,
    PythonStrategyOutput* output
);

/**
 * Free resources allocated by trading_strategies_run
 * 
 * Call this after processing the output to prevent memory leaks.
 * 
 * @param output Output structure from trading_strategies_run
 */
void trading_strategies_free_output(PythonStrategyOutput* output);

/**
 * Get human-readable error message for return code
 * 
 * @param return_code AsirikuyReturnCode value
 * @return Error message string (static, do not free)
 */
const char* trading_strategies_get_error_message(int return_code);

/**
 * Get library version string
 * 
 * @return Version string (static, do not free)
 */
const char* trading_strategies_get_version(void);

/**
 * Initialize library (optional, for future use)
 * 
 * @return SUCCESS on success
 */
int trading_strategies_init(void);

/**
 * Cleanup library (optional, for future use)
 */
void trading_strategies_cleanup(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TRADING_STRATEGIES_PYTHON_API_H_ */

